WebApplication1/WebApplication1/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    
    public class ApplicationsController : Controller
    {
        private DbModel db = new DbModel();

        [HttpGet]
        public ActionResult CreateApplication(int? tourId)
        {
            var tour = db.Tours.Where(x => x.Id == tourId).FirstOrDefault();
            if (tour != null)
            {
                Applications newApplication = new Applications();
                ViewBag.tourId = (int)tourId;
                ViewBag.tour = tour;
                return View(newApplication);
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }
        [HttpPost]
        public ActionResult CreateApplication(Applications application, int tourId)
        {
            var tour = db.Tours.Where(x => x.Id == tourId).FirstOrDefault();
            if(tour != null)
            {
                application.tour_id = tourId;
                application.order_date = System.DateTime.Now;
                db.Applications.Add(application);
                db.SaveChanges();
                ModelState.Clear();
                return View("CreateApplication");
            }
            else
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }
    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private DbModel db = new DbModel();

        public ActionResult Index()
        {
            var tours = db.Tours.ToList();
            tours.Reverse();
            return View(tours);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult TourFilter(string tourPrice)
        {

            if(tourPrice == "0-300")
            {
                var tours = db.Tours.Where(x => x.price <= 300 && x.price > 0).ToList();
                return View("Index", tours);
            }
            if(tourPrice == "300-500")
            {
                var tours = db.Tours.Where(x => x.price <= 500 && x.price >= 300).ToList();
                return View("Index", tours);
            }
            if(tourPrice == "500-800")
            {
                var tours = db.Tours.Where(x => x.price <= 800 && x.price >= 500).ToList();
                return View("Index", tours);
            }
            if(tourPrice == "800+")
            {
                var tours = db.Tours.Where(x => x.price >= 800).ToList();
                return View("Index", tours);
            }
            return View("Index");
        }
    }
}

WebApplication1/WebApplication1/Controllers/ToursController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using System.IO;

namespace WebApplication1.Controllers
{

    public class ToursController : Controller
    {

        private DbModel db = new DbModel();

        [HttpGet]
        public ActionResult ViewTour(int? tourId )
        {
            var tour = db.Tours.Find(tourId);
            if (tour != null)
            {
                return View(tour);
            }
            return View("Index", "Home");
        }

        [HttpGet]
        public ActionResult CreateTour()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateTour(Tours newTour, HttpPostedFileBase tour_img)
        {
            string fileName = System.IO.Path.GetFileName(tour_img.FileName);
            newTour.img_path = "/Files/" + fileName;
            tour_img.SaveAs(Server.MapPath("~/Files/" + fileName));
            db.Tours.Add(newTour);
            db.SaveChanges();

            ViewBag.SuccessMessage = "Tour created successfuly";
            return View(newTour);
        }
        [HttpGet]
        public ActionResult DeleteTour(int? tourId)
        {
            if (Session["userId"] != null)
            {
                if (tourId == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                using (DbModel db = new DbModel())
                {
                    var tourToDelete = db.Tours.Find(tourId);
                    if (tourToDelete != null)
                    {
                        db.Tours.Remove(tourToDelete);
                        db.SaveChanges();
                        ViewBag.SuccessMessage = "Tour deleted successfully";
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult UpdateTour(int? tourId)
        {
            var tourToDelete = db.Tours.Find(tourId);
            return View(tourToDelete);
        }

        [HttpPost]
        public ActionResult UpdateTour(Tours tour, HttpPostedFileBase tour_img)
        {

            var tourToUpdate = db.Tours.FirstOrDefault(x => x.Id == tour.Id);
            tourToUpdate.name = tour.name;
            tourToUpdate.hotel_id = tour.hotel_id;

            if (tour_img != null)
            {
                string fileName = System.IO.Path.GetFileName(tour_img.FileName);
                tour.img_path = "/Files/" + fileName;
                tour_img.SaveAs(Server.MapPath("~/Files/" + fileName));
                tourToUpdate.img_path = tour.img_path;
            }

            tourToUpdate.departure_city = tour.departure_city;
            tourToUpdate.price = tour.price;
            tourToUpdate.description = tour.description;
            db.SaveChanges();

            ViewBag.SuccessMessage = "Tour successfuly updated";
            return View(tourToUpdate);
        }

        
    }
}

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@model List<WebApplication1.Models.Tours>
@{
    ViewBag.Title = "Tour Agency";
}

<div class="jumbotron">
    <h1>Tour Agency</h1>
    <p class="lead">Our service provides the best.</p>
    @if (Session["role_id"] != null && Session["role_id"].ToString() == "1")
    {
        <p><a href="@Url.Action("CreateTour", "Tours")" class="btn btn-primary btn-lg">New Tour &raquo;</a></p>
    }
</div>

<div class="row">
    <hr />
    @using (Html.BeginForm("TourFilter", "Home", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
    <div class="form-inline">
        <label class="control-label">Tour price: </label>
        <select name="tourPrice" class="form-control">
            <option>
                0-300
            </option>
            <option>
                300-500
            </option>
            <option>
                500-800
            </option>
            <option>
                800+
            </option>
        </select>
        <a href="@Url.Action("Index", "Home")" class="btn btn-default">Clear all filters</a>
        <input type="submit" value="Filter" class="btn btn-default" />
    </div>
    }
    <hr />
    @if (Model != null)
    {
        foreach (var tour in Model)
        {
    <div class="col-lg-10">

        @{
            <a href="@Url.Action("ViewTour", "Tours", new { tourId = tour.Id})"><h2>@tour.name</h2></a>
            <a href="@Url.Action("ViewTour", "Tours", new { tourId = tour.Id})">
                <img src="@tour.img_path" name="tour_img" style="width: 100%; height: auto" />
            </a>
            <h6>@tour.departure_city</h6>
            <h4>@tour.price $</h4>
            <p>@tour.description</p>
            if (Session["role_id"] != null && Session["role_id"].ToString() == "1")
            {
                <p><a href="@Url.Action("DeleteTour", "Tours", new { tourId = tour.Id })" class="btn btn-primary btn-lg">Delete Tour&raquo;</a></p>
                <p><a href="@Url.Action("UpdateTour", "Tours", new { tourId = tour.Id })" class="btn btn-primary btn-lg">Update Tour&raquo;</a></p>
            }
            else if (Session["role_id"] == null || Session["role_id"].ToString() == "3")
            {
                <p><a href="@Url.Action("CreateApplication", "Applications", new { tourId = tour.Id })" class="btn btn-primary btn-lg">Buy Tour&raquo;</a></p>
            }
            <hr />
        }
    </div>
        }
    }


</div>